export const products = [
	{
		id: 1,
		category: 'Tech',
		name: 'Mystery Tech Box',
		image: '/mysterybox-tech.jpg',
		price: 99.99,
		description: 'What tech treasures await? Only one kind of person will find out: YOU!',
		detailDescription: 'Ein spannendes Technik-Paket voller Überraschungen! Von Gadgets bis zu Smart-Home-Produkten.',
	},
	{
		id: 2,
		category: 'Fashion',
		name: 'Mystery Fashion Box',
		image: '/mysteryBox/mysterybox-fashion.jpg',
		price: 79.99,
		description: 'Unleash your inner fashion icon! Prepare for a stylish surprise.',
		detailDescription: 'Stylische Überraschungen für deinen Kleiderschrank! Aktuelle Trends und zeitlose Klassiker.',
	},
	{
		id: 3,
		category: 'Food',
		name: 'Mystery Food Box',
		image: '/mysteryBox/placeholder-box1.jpg',
		price: 49.99,
		description: 'A culinary adventure awaits! Taste the unexpected.',
		detailDescription: 'Kulinarische Entdeckungsreise mit ausgewählten Spezialitäten und Überraschungen.',
	},
	{
		id: 4,
		category: 'Deluxe',
		name: 'Mystery Deluxe Box',
		image: '/mysteryBox/mysterybox-deluxe.jpeg',
		price: 149.99,
		description: 'Ein Hauch von Luxus und Überraschung.',
		detailDescription: 'Kulinarische Entdeckungsreise mit ausgewählten Spezialitäten und Überraschungen.',
	},
	{
		id: 5,
		category: 'Mega',
		name: 'Mystery Mega Box',
		image: '/mysteryBox/mysterybox-mega.jpg',
		price: 199.99,
		description: 'Große Überraschungen für große Freude.',
		detailDescription: 'Kulinarische Entdeckungsreise mit ausgewählten Spezialitäten und Überraschungen.',
	},
	{
		id: 6,
		category: 'Ultimate',
		name: 'Mystery Ultimate Box',
		image: '/mysteryBox/mysterybox-ultimate.jpg',
		price: 299.99,
		description: 'Die ultimative Überraschungserfahrung.',
		detailDescription: 'Kulinarische Entdeckungsreise mit ausgewählten Spezialitäten und Überraschungen.',
	},
    {
		id: 7,
		name: 'XXL Premium Mystery Box',
		price: 99.99,
		originalPrice: 279.99,
		image: '/mysteryBox/mysterybox-premium1.jpg',
		description: '10 KG Überraschungsbox'
	  },
	  {
		id: 8,
		name: 'Starter Mystery Box',
		price: 39.99,
		originalPrice: 120.00,
		image: '/mysteryBox/starterbox.jpg',
		description: '3 KG Überraschungskarton'
	  }
];